// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZEgC7DMLXe0ZMXGLiX4OUqfOracdJhGg',
    appId: '1:173626036175:web:cb2bc99f4c57e75ca20cba',
    messagingSenderId: '173626036175',
    projectId: 'sneaker-shop-e2612',
    authDomain: 'sneaker-shop-e2612.firebaseapp.com',
    storageBucket: 'sneaker-shop-e2612.appspot.com',
    measurementId: 'G-J5L0JXJPBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJFNtYBLUPfLU6CSyK5ERbyVUqsdoKhw',
    appId: '1:173626036175:android:1ba3ff41ab18a982a20cba',
    messagingSenderId: '173626036175',
    projectId: 'sneaker-shop-e2612',
    storageBucket: 'sneaker-shop-e2612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiK0r76c7xYbp0No4ngcJiSujNpOttEoo',
    appId: '1:173626036175:ios:b9489af84c0ae538a20cba',
    messagingSenderId: '173626036175',
    projectId: 'sneaker-shop-e2612',
    storageBucket: 'sneaker-shop-e2612.appspot.com',
    iosBundleId: 'com.example.sneakerShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiK0r76c7xYbp0No4ngcJiSujNpOttEoo',
    appId: '1:173626036175:ios:b9489af84c0ae538a20cba',
    messagingSenderId: '173626036175',
    projectId: 'sneaker-shop-e2612',
    storageBucket: 'sneaker-shop-e2612.appspot.com',
    iosBundleId: 'com.example.sneakerShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZEgC7DMLXe0ZMXGLiX4OUqfOracdJhGg',
    appId: '1:173626036175:web:1d1b853f34e63917a20cba',
    messagingSenderId: '173626036175',
    projectId: 'sneaker-shop-e2612',
    authDomain: 'sneaker-shop-e2612.firebaseapp.com',
    storageBucket: 'sneaker-shop-e2612.appspot.com',
    measurementId: 'G-67F8E9RCH6',
  );
}
